# Generated by Django 2.2.8 on 2019-12-09 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('pl', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('role_name', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('realname', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=32)),
                ('phone', models.CharField(max_length=11)),
                ('gender', models.CharField(max_length=2)),
                ('engineer', models.CharField(max_length=10, verbose_name='职位')),
                ('id_card', models.CharField(max_length=20)),
                ('school', models.CharField(max_length=20)),
                ('gradution_time', models.DateField()),
                ('education', models.CharField(max_length=20)),
                ('pre_job', models.CharField(max_length=20)),
                ('entry_time', models.DateField()),
                ('spical_date', models.DateField()),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Group', verbose_name='用户所属组')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Role', verbose_name='用户角色')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
