# Generated by Django 2.2.8 on 2020-01-07 06:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=20, verbose_name='组名'),
        ),
        migrations.AlterField(
            model_name='group',
            name='pl',
            field=models.CharField(max_length=10, verbose_name='组长'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='education',
            field=models.CharField(max_length=20, verbose_name='学历'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='email',
            field=models.EmailField(max_length=32, verbose_name='邮箱'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='entry_time',
            field=models.DateField(verbose_name='入职时间'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='gender',
            field=models.CharField(max_length=2, verbose_name='性别'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_users', to='account.Group', verbose_name='用户所属组'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='id_card',
            field=models.CharField(max_length=20, verbose_name='身份证'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='phone',
            field=models.CharField(max_length=11, verbose_name='手机号'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='pre_job',
            field=models.CharField(max_length=20, verbose_name='上一份工作'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='realname',
            field=models.CharField(max_length=10, verbose_name='真实姓名'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='school',
            field=models.CharField(max_length=20, verbose_name='毕业学校'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='spical_date',
            field=models.DateField(verbose_name='生日'),
        ),
    ]
