# Generated by Django 2.2.8 on 2020-02-29 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20200110_1456'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userinfo',
            old_name='spical_date',
            new_name='birth_day',
        ),
    ]
