# Generated by Django 2.2.10 on 2020-05-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20200304_1345'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': '用户小组', 'verbose_name_plural': '用户小组'},
        ),
        migrations.AlterModelOptions(
            name='role',
            options={'verbose_name': '用户角色', 'verbose_name_plural': '用户角色'},
        ),
        migrations.AlterModelOptions(
            name='userinfo',
            options={'verbose_name': '用户信息', 'verbose_name_plural': '用户信息'},
        ),
    ]
