# Generated by Django 2.2.10 on 2020-07-22 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20200512_1549'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonLinks',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('links_name', models.CharField(max_length=30, verbose_name='常用链接')),
                ('click_number', models.IntegerField(default=0, verbose_name='点击次数')),
                ('url', models.CharField(default=0, max_length=100, verbose_name='url地址')),
            ],
            options={
                'verbose_name': '常用链接',
                'verbose_name_plural': '常用链接',
            },
        ),
    ]
