# Generated by Django 2.2.10 on 2020-04-09 06:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asset', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='area',
            field=models.CharField(default=None, max_length=4, verbose_name='区域'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_created', to=settings.AUTH_USER_MODEL, verbose_name='创建者'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='complaint',
            name='description',
            field=models.TextField(blank=True, verbose_name='问题描述'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='oa_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='OA流程号'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complete_time',
            field=models.DateField(blank=True, verbose_name='措施完成时间'),
        ),
        migrations.CreateModel(
            name='NodeMessage',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pl_name', models.CharField(blank=True, max_length=50, verbose_name='组长')),
                ('pl_decide', models.CharField(blank=True, max_length=50, verbose_name='组长意见')),
                ('pl_notes', models.CharField(blank=True, max_length=50, verbose_name='组长意见说明')),
                ('pl_time', models.DateTimeField(verbose_name='组长处理时间')),
                ('m_name', models.CharField(blank=True, max_length=50, verbose_name='经理')),
                ('m_decide', models.CharField(blank=True, max_length=50, verbose_name='经理意见')),
                ('m_notes', models.CharField(blank=True, max_length=50, verbose_name='经理意见说明')),
                ('m_time', models.DateTimeField(verbose_name='经理处理时间')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asset.TecContent', verbose_name='优秀实践')),
            ],
        ),
    ]
