# Generated by Django 2.2.10 on 2020-04-24 17:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200409_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='analysis_time',
            field=models.DateTimeField(blank=True,  verbose_name='分析完成时间'),
            preserve_default=False,
        ),
    ]
