# Generated by Django 2.2.8 on 2020-01-10 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20200107_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='complete_time',
            field=models.DateTimeField(verbose_name='分析完成时间'),
        ),
    ]
