# Generated by Django 2.2.10 on 2020-05-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_complaint_analysis_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articles',
            options={'ordering': ('-publish',), 'verbose_name': '技术文章', 'verbose_name_plural': '技术文章'},
        ),
        migrations.AlterModelOptions(
            name='complaint',
            options={'ordering': ('-created_at',), 'verbose_name_plural': '客诉记录'},
        ),
        migrations.AlterModelOptions(
            name='teccontent',
            options={'ordering': ('-created_at',), 'verbose_name_plural': '优秀实践'},
        ),
    ]
