# Generated by Django 2.2.8 on 2020-03-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0003_auto_20200110_1456'),
    ]

    operations = [
        migrations.AddField(
            model_name='teccontent',
            name='status',
            field=models.CharField(default=1, max_length=2, verbose_name='状态'),
            preserve_default=False,
        ),
    ]
