# Generated by Django 2.2.10 on 2020-06-18 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0004_auto_20200512_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='teccontent',
            name='award',
            field=models.CharField(blank=True, max_length=50, verbose_name='奖项'),
        ),
        migrations.AlterField(
            model_name='teccontent',
            name='tec_tag',
            field=models.ManyToManyField(blank=True, related_name='tec_tag', to='asset.TecTag', verbose_name='类别'),
        ),
    ]
