# Generated by Django 2.2.10 on 2020-07-14 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0006_auto_20200630_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='analysis_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='分析完成时间'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='category',
            field=models.CharField(blank=True, max_length=10, verbose_name='问题分类'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='cfile',
            field=models.FileField(blank=True, upload_to='complaint_file', verbose_name='材料附件'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='closed_time',
            field=models.DateField(blank=True, null=True, verbose_name='计划闭环时间'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='complete_time',
            field=models.DateField(blank=True, null=True, verbose_name='措施完成时间'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='oa_number',
            field=models.CharField(max_length=20, verbose_name='OA流程号'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, max_length=50, verbose_name='措施状态'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='tester',
            field=models.CharField(blank=True, max_length=10, verbose_name='分析责任人'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='version',
            field=models.CharField(max_length=30, verbose_name='软件版本'),
        ),
    ]
