# Generated by Django 2.2.10 on 2020-09-11 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_commonlinks'),
        ('asset', '0007_auto_20200714_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='专利名称')),
                ('type', models.CharField(max_length=50, verbose_name='类别')),
                ('submit_time', models.DateField(verbose_name='提交时间')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('status', models.CharField(max_length=50, verbose_name='状态')),
                ('patent_id', models.CharField(max_length=50, verbose_name='专利号')),
                ('award', models.CharField(max_length=50, verbose_name='奖励')),
                ('file', models.FileField(upload_to='patent_files', verbose_name='专利申请材料')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_patent', to='account.UserInfo', verbose_name='作者')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='group_patent', to='account.Group', verbose_name='小组')),
            ],
            options={
                'verbose_name': '专利',
                'verbose_name_plural': '专利',
                'ordering': ('-created_at',),
            },
        ),
    ]
