# Generated by Django 2.2.10 on 2021-01-29 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0008_patent'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50, verbose_name='项目名称')),
                ('type', models.CharField(max_length=50, verbose_name='项目类型')),
                ('created_at', models.DateField(auto_now_add=True, verbose_name='创建时间')),
                ('completed_time', models.DateField(blank=True, null=True, verbose_name='结项时间')),
                ('coder', models.CharField(blank=True, max_length=50, null=True, verbose_name='软件owner')),
                ('developer', models.CharField(blank=True, max_length=50, null=True, verbose_name='硬件owner')),
                ('tester', models.CharField(blank=True, max_length=50, null=True, verbose_name='测试owner')),
                ('newbug_percent', models.CharField(blank=True, help_text='百分数', max_length=20, null=True, verbose_name='缺陷引入率')),
                ('reopen_count', models.IntegerField(blank=True, help_text='正整数', null=True, verbose_name='缺陷回归不通过数')),
                ('missing_percent', models.CharField(blank=True, help_text='百分数', max_length=20, null=True, verbose_name='漏测率')),
                ('nocase_found', models.IntegerField(blank=True, null=True, verbose_name='用例外发现bug数')),
                ('bbit_round', models.IntegerField(blank=True, null=True, verbose_name='迭代/BBIT轮次')),
                ('tr4_round', models.IntegerField(blank=True, null=True, verbose_name='TR4/正常轮次')),
                ('reject_count', models.IntegerField(blank=True, help_text='正整数', null=True, verbose_name='驳回轮次')),
                ('reject_reason', models.TextField(blank=True, null=True, verbose_name='转测试驳回原因')),
                ('delay', models.IntegerField(blank=True, help_text='项目进度偏差天数', null=True, verbose_name='项目进度偏差')),
                ('delay_reason', models.TextField(blank=True, null=True, verbose_name='偏差原因')),
                ('day_round', models.FloatField(blank=True, null=True, verbose_name='转测试天数每轮')),
                ('per_version', models.FloatField(blank=True, null=True, verbose_name='平均人力天/B版本')),
                ('perf_count', models.IntegerField(blank=True, null=True, verbose_name='关键性能超越竞品数')),
                ('beta_bug', models.IntegerField(blank=True, null=True, verbose_name='Beta/内测问题数')),
                ('customer_bug', models.IntegerField(blank=True, null=True, verbose_name='OA客诉问题数')),
                ('quality_issue', models.IntegerField(blank=True, null=True, verbose_name='重大质量事故')),
                ('solution', models.CharField(blank=True, help_text='百分数', max_length=20, null=True, verbose_name='解决方案体验满意度')),
                ('tec_count', models.IntegerField(blank=True, null=True, verbose_name='技术开发数')),
                ('cost_percent', models.CharField(blank=True, max_length=50, null=True, verbose_name='目标成本达成率')),
                ('pcb_count', models.IntegerField(blank=True, null=True, verbose_name='PCB打板次数')),
                ('item_percent', models.CharField(blank=True, help_text='百分数', max_length=50, null=True, verbose_name='材料优选率')),
                ('note', models.TextField(blank=True, null=True, verbose_name='项目备注')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'ordering': ('-created_at',),
            },
        ),
    ]
