# Generated by Django 2.2.10 on 2021-03-29 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0010_auto_20210201_1420'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='changed',
            field=models.IntegerField(blank=True, help_text='正整数', null=True, verbose_name='需求变更次数'),
        ),
    ]
