# Generated by Django 2.2.18 on 2021-04-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0011_project_changed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='changed',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='需求变更次数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='day_round',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='转测试天数每轮'),
        ),
        migrations.AlterField(
            model_name='project',
            name='delay',
            field=models.CharField(blank=True, help_text='项目进度偏差天数', max_length=20, null=True, verbose_name='项目进度偏差'),
        ),
        migrations.AlterField(
            model_name='project',
            name='nocase_found',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='用例外发现bug数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pcb_count',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='PCB打板次数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='per_version',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='平均人力天/B版本'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reject_count',
            field=models.CharField(blank=True, help_text='正整数', max_length=20, null=True, verbose_name='驳回轮次'),
        ),
        migrations.AlterField(
            model_name='project',
            name='reopen_count',
            field=models.CharField(blank=True, help_text='正整数', max_length=20, null=True, verbose_name='缺陷回归不通过数'),
        ),
        migrations.AlterField(
            model_name='project',
            name='test_round',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='测试轮次'),
        ),
    ]
