# Generated by Django 2.2.8 on 2020-01-16 07:05

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200116_1443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlecolumn',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='article_column', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 16, 7, 5, 3, 568507, tzinfo=utc)),
        ),
    ]
