# Generated by Django 6.0.4 on 2026-04-19 10:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0002_auto_20200512_1549'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='articlepost',
            new_name='article_art_id_e7a7d5_idx',
            old_fields=('id', 'slug'),
        ),
    ]
