# Generated by Django 2.2.8 on 2020-01-20 01:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_auto_20200116_1505'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 20, 1, 46, 54, 665244, tzinfo=utc)),
        ),
    ]
