# Generated by Django 2.2.8 on 2020-03-04 03:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0004_auto_20200120_0946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 4, 3, 31, 44, 77740, tzinfo=utc)),
        ),
    ]
