# Generated by Django 2.2.10 on 2020-03-10 02:08

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_auto_20200304_1338'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articlepost',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 10, 2, 8, 4, 985572, tzinfo=utc)),
        ),
    ]
