# Generated by Django 2.2.10 on 2020-03-30 01:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0005_auto_20200304_1345'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integral',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('total', models.IntegerField(verbose_name='总积分')),
                ('joined', models.IntegerField(verbose_name='参加培训积分')),
                ('teached_group', models.IntegerField(verbose_name='组织小组培训积分')),
                ('teached', models.IntegerField(verbose_name='组织部门培训积分')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_integral', to='account.UserInfo', verbose_name='姓名')),
            ],
            options={
                'ordering': ('total',),
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('cname', models.CharField(max_length=30, verbose_name='课程名')),
                ('range', models.CharField(max_length=50, verbose_name='课程范围')),
                ('course_time', models.DateTimeField(verbose_name='培训时间')),
                ('address', models.CharField(max_length=30, verbose_name='培训地点')),
                ('file_name', models.FileField(upload_to='course_files', verbose_name='附件')),
                ('cdescription', models.CharField(blank=True, max_length=150, verbose_name='课程概述')),
                ('student', models.ManyToManyField(blank=True, related_name='course_joined', to='account.UserInfo')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_teacher', to='account.UserInfo', verbose_name='主讲人')),
            ],
            options={
                'ordering': ('-course_time',),
            },
        ),
    ]
