# Generated by Django 2.2.8 on 2020-03-04 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='group_name',
        ),
        migrations.AddField(
            model_name='course',
            name='cdescription',
            field=models.CharField(blank=True, max_length=150, verbose_name='课程概述'),
        ),
        migrations.AlterField(
            model_name='course',
            name='file_name',
            field=models.FileField(upload_to='course_files', verbose_name='附件'),
        ),
    ]
