# Generated by Django 2.2.10 on 2020-03-10 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0002_auto_20200304_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='course_teacher', to='account.UserInfo', verbose_name='主讲人'),
        ),
    ]
