# Generated by Django 2.2.10 on 2020-03-24 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('training', '0003_auto_20200310_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_time',
            field=models.DateTimeField(verbose_name='培训时间'),
        ),
    ]
